language: php

php:
  - 7.2

install:
  - composer install

script:
  - composer run test:cs
  - composer run test:unit -- --coverage-clover build/logs/clover.xml --whitelist src

after_success:
  - composer require php-coveralls/php-coveralls '^2.0' --dev
  - ./vendor/bin/php-coveralls -v --coverage_clover=build/logs/clover.xml
